### ISSUE TITLE
action # vendimia is only processing last campo of last bodega, not previous records

### ISSUE THREAD

**Issue by Japoivvb** [Miguelstucom/hibernate#3]
1. when vendimia is processed previous records are not being processed, e.g. vid 3,4,17,18

2. set issue label as bug to be tracked

3. commit message with #numberIssue verb(in 3rd person) +  details 
e.g. #1 adds incremental id logic

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by Miguelstucom** [comment]
![Captura](https://github.com/Miguelstucom/hibernate/assets/114105189/add12cf0-013c-4657-8e28-97bb636e173d)

**Comment by Japoivvb** [comment]
1. ok
2. ok
3. ok
4. ok
5. ok
