### ISSUE TITLE
add new field precio to vid model 

### ISSUE THREAD

**Issue by Japoivvb** [Miguelstucom/hibernate#4]
1. add double price attribute to vid model and verify everything is working again

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb(in 3rd person) +  details 

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by Miguelstucom** [comment]
![image](https://github.com/Miguelstucom/hibernate/assets/114105189/4530efd7-5fe5-4dc1-b18d-f1e6e59790a3)

**Comment by Japoivvb** [comment]
1. ok
2. ok
3. ok
4. ok
5. ok
