### ISSUE TITLE
add new method to show total price based vid.precio for all vids

### ISSUE THREAD

**Issue by Japoivvb** [Miguelstucom/hibernate#5]
1. after current showAllCampos() create a new method showTotalPrice()

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb(in 3rd person) +  details 

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by Miguelstucom** [comment]
![image](https://github.com/Miguelstucom/hibernate/assets/114105189/6c62518f-1a5c-4e1c-878e-a1af29f8e7b9)

**Comment by Miguelstucom** [comment]
![image](https://github.com/Miguelstucom/hibernate/assets/114105189/2d145487-ba9a-46d1-ac70-653742560ffd)

**Comment by Japoivvb** [comment]
1. ok
2. ok
3. ok
4. ok
5. ok
