### ISSUE TITLE
migrate application from SQL database to NoSQL database

### ISSUE THREAD

**Issue by Japoivvb** [Miguelstucom/hibernate#6]
1. modify application to use only mongoDB, remove Hibernate(MySQL) sentence once everything is working

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb(in 3rd person) +  details 

4. include screenshot(from each collection) in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by Miguelstucom** [comment]
![image](https://github.com/Miguelstucom/hibernate/assets/114105189/c691b17e-73b4-4b09-b7ff-b0daa10dc2cd)
![image](https://github.com/Miguelstucom/hibernate/assets/114105189/db1902af-5572-4729-b701-5290aa2722ea)
![image](https://github.com/Miguelstucom/hibernate/assets/114105189/8019864f-bf74-4edd-93ea-b15925c98b10)
![image](https://github.com/Miguelstucom/hibernate/assets/114105189/a1e5216c-7072-49db-b9e9-494b8d2c64ea)

**Comment by Miguelstucom** [comment]
![image](https://github.com/Miguelstucom/hibernate/assets/114105189/dbe8537b-626b-492e-a3aa-435fa3fce639)
![image](https://github.com/Miguelstucom/hibernate/assets/114105189/19430f8a-9725-4e72-87df-41602f0b9705)
![image](https://github.com/Miguelstucom/hibernate/assets/114105189/b7fadcf3-6174-4eff-8080-f170845f7f75)

**Comment by Japoivvb** [comment]
1. ok
2. ko, enhancement instead issue
3. ok
4. ok
5. ok
great job, one of the best of the class, as always
